"""Regenerate a survey timeline (TikZ): the two surveys' observing windows at one Roman footprint
sightline, drawn on the simulation clock (day 0 = 2026-04-11, the first Rubin bulge visit). Run from
the repo root. Reads the same visit lists the simulator reads and matches epochs with the
simulator's own coverage tests (Rubin: 1.75 deg circle; Roman: analysis/gbtds_geometry), keeping
unique times.

    .roman/bin/python Report/overview/make_timeline.py            # adopted layout (Deviation 69)
        -> Report/overview_v2/timeline.tex, sightline (0.40, -1.45), on a detector in both rolls
    .roman/bin/python Report/overview/make_timeline.py --legacy   # the old report's figure
        -> Report/overview/timeline.tex, from Baseline/legacy_layout40395/, sightline (0.4, -1.2)
"""
import argparse
import datetime as dt
import os
import sys

import numpy as np

sys.path.insert(0, "analysis")
import gbtds_geometry as G                              # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument("--legacy", action="store_true", help="the pre-Deviation-69 runs' visit lists")
args = ap.parse_args()
BASE = "Baseline/legacy_layout40395" if args.legacy else "Baseline"
OUT = "Report/overview/timeline.tex" if args.legacy else "Report/overview_v2/timeline.tex"

RUBIN_FOV = G.FOV_RUBIN
TOBS = 3652.425
DAY0 = dt.date(2026, 4, 11)
GAP = 20.0          # a gap longer than this starts a new observing window
WIDTH_CM = 14.5

def near(l, b, l0, b0, r):
    l = np.where(l > 180, l - 360, l)
    return np.hypot(l - l0, b - b0) < r

def windows(t):
    t = np.unique(t)
    cut = np.where(np.diff(t) > GAP)[0]
    lo, hi = np.r_[0, cut + 1], np.r_[cut, len(t) - 1]
    return [(t[a], t[z], z - a + 1) for a, z in zip(lo, hi)], len(t)

visits = G.read_roman_visits(f'{BASE}/RomanBaseline.dat')
rub = np.loadtxt(f'{BASE}/BulgeBaseline.dat', comments='#', usecols=(3, 4, 5))
if args.legacy:
    l0, b0 = visits["l"].iloc[0], visits["b"].iloc[0]     # the first Roman field centre
else:
    l0, b0 = 0.40, -1.45                                  # field 2, on a detector in both rolls
    assert G.on_detector(l0, b0).all(), "timeline sightline must see both rolls"
rom_w, n_rom = windows(visits["time"].to_numpy()[G.visit_covers(visits, l0, b0)])
rub_w, n_rub = windows(rub[near(rub[:, 0], rub[:, 1], l0, b0, RUBIN_FOV), 2])

x = lambda d: f'{WIDTH_CM * d / TOBS:.3f}'
out = [f'% GENERATED by Report/overview/make_timeline.py -- do not edit.',
       f'% sightline (l,b) = ({l0:.2f}, {b0:.2f}); Rubin {n_rub} epochs, Roman {n_rom} epochs.',
       f'\\def\\tlL{{{l0:.1f}}}\\def\\tlB{{{b0:.1f}}}\\def\\tlNrub{{{n_rub:,}}}\\def\\tlNrom{{{n_rom:,}}}'.replace(',', '{,}'),
       '\\begin{tikzpicture}[x=1cm,y=1cm]']
for yr in range(2027, 2037):
    d = (dt.date(yr, 1, 1) - DAY0).days
    out.append(f'\\draw[black!25] ({x(d)},-0.15) -- ({x(d)},1.55);'
               f'\\node[font=\\scriptsize,anchor=north] at ({x(d)},-0.15) {{{yr}}};')
out.append(f'\\draw[black!60] (0,0) -- ({WIDTH_CM},0);')
out.append('\\node[font=\\small,anchor=east] at (-0.1,1.1) {Rubin};')
out.append('\\node[font=\\small,anchor=east] at (-0.1,0.4) {Roman};')
for a, z, n in rub_w:
    z = max(z, a + 2.0)                             # single nights stay visible
    out.append(f'\\fill[orange!70] ({x(a)},0.9) rectangle ({x(z)},1.3);')
for a, z, n in rom_w:
    style = 'blue!75' if n > 1000 else 'blue!25'    # high cadence: thousands of exposures
    out.append(f'\\fill[{style}] ({x(a)},0.2) rectangle ({x(z)},0.6);')
out.append('\\end{tikzpicture}')
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w').write('\n'.join(out) + '\n')
for a, z, n in rom_w:
    print(f'Roman {a:8.1f} {z:8.1f} {n:6d}')
print(f'sightline ({l0}, {b0}); Rubin {n_rub} unique epochs in {len(rub_w)} windows; Roman {n_rom}')
