"""Regenerate Report/overview/timeline.tex: the two surveys' observing windows at one Roman
footprint sightline, drawn on the simulation clock (day 0 = 2026-04-11, the first Rubin bulge
visit). Run from the repo root. Reads the same visit lists the simulator reads, and matches epochs
with the simulator's fields of view (Rubin 1.75 deg, Roman 0.3003 deg), keeping unique times."""
import datetime as dt
import numpy as np

RUBIN_FOV, ROMAN_FOV = 1.75, 0.3003
TOBS = 3652.425
DAY0 = dt.date(2026, 4, 11)
GAP = 20.0          # a gap longer than this starts a new observing window
WIDTH_CM = 14.5

def near(l, b, l0, b0, r):
    l = np.where(l > 180, l - 360, l)
    return np.hypot(l - l0, b - b0) < r

def windows(t):
    t = np.unique(t)
    cut = np.where(np.diff(t) > GAP)[0]
    lo, hi = np.r_[0, cut + 1], np.r_[cut, len(t) - 1]
    return [(t[a], t[z], z - a + 1) for a, z in zip(lo, hi)], len(t)

rom = np.loadtxt('Baseline/RomanBaseline.dat', comments='#', usecols=(3, 4, 5))
rub = np.loadtxt('Baseline/BulgeBaseline.dat', comments='#', usecols=(3, 4, 5))
l0, b0 = rom[0, 0], rom[0, 1]                      # the first Roman field centre
rom_w, n_rom = windows(rom[near(rom[:, 0], rom[:, 1], l0, b0, ROMAN_FOV), 2])
rub_w, n_rub = windows(rub[near(rub[:, 0], rub[:, 1], l0, b0, RUBIN_FOV), 2])

x = lambda d: f'{WIDTH_CM * d / TOBS:.3f}'
out = [f'% GENERATED by Report/overview/make_timeline.py -- do not edit.',
       f'% sightline (l,b) = ({l0:.2f}, {b0:.2f}); Rubin {n_rub} epochs, Roman {n_rom} epochs.',
       f'\\def\\tlL{{{l0:.1f}}}\\def\\tlB{{{b0:.1f}}}\\def\\tlNrub{{{n_rub:,}}}\\def\\tlNrom{{{n_rom:,}}}'.replace(',', '{,}'),
       '\\begin{tikzpicture}[x=1cm,y=1cm]']
for yr in range(2027, 2037):
    d = (dt.date(yr, 1, 1) - DAY0).days
    out.append(f'\\draw[black!25] ({x(d)},-0.15) -- ({x(d)},1.55);'
               f'\\node[font=\\scriptsize,anchor=north] at ({x(d)},-0.15) {{{yr}}};')
out.append(f'\\draw[black!60] (0,0) -- ({WIDTH_CM},0);')
out.append('\\node[font=\\small,anchor=east] at (-0.1,1.1) {Rubin};')
out.append('\\node[font=\\small,anchor=east] at (-0.1,0.4) {Roman};')
for a, z, n in rub_w:
    z = max(z, a + 2.0)                             # single nights stay visible
    out.append(f'\\fill[orange!70] ({x(a)},0.9) rectangle ({x(z)},1.3);')
for a, z, n in rom_w:
    style = 'blue!75' if n > 1000 else 'blue!25'    # high cadence: thousands of exposures
    out.append(f'\\fill[{style}] ({x(a)},0.2) rectangle ({x(z)},0.6);')
out.append('\\end{tikzpicture}')
open('Report/overview/timeline.tex', 'w').write('\n'.join(out) + '\n')
for a, z, n in rom_w:
    print(f'Roman {a:8.1f} {z:8.1f} {n:6d}')
print(f'sightline ({l0}, {b0}); Rubin {n_rub} unique epochs in {len(rub_w)} windows; Roman {n_rom}')
