#ifndef DATA_PRODUCTS_H
#define DATA_PRODUCTS_H

// GENERATED by tools/sync_data_products.py from the data files -- DO NOT EDIT BY HAND;
// re-run the script (python3 tools/sync_data_products.py) after regenerating any data file.
// `python3 tools/sync_data_products.py --check` (or `make check-data`) says whether this file is stale.
//
// Numbers that DESCRIBE THE DATA FILES on disk: row counts, catalogue mean masses and the bright-star
// floor of an error table. These are measurements of the data, not choices; the read guards in
// src/run/inputs.cpp fire on a row-count mismatch. Model and survey choices live in config/parameters.h.

// ---- Error tables: files/sigmaA_LSST.txt (96 rows), files/sigma_roman.txt (123 rows) ----
constexpr int Na = 96;     //rows in "sigmaA_LSST.txt"
constexpr int NaRoman = 123;  // rows in sigma_roman.txt

// Bright-star floor of files/sigmaA_LSST.txt (its smallest error value), as shipped. config/parameters.h
// (section 4, LSST_AST_RENORM) divides the per-visit floor by it; see the note there.
constexpr double LSST_AST_TABLE_FLOOR = 0.3739576; //mas

// ---- CMD/components/*.dat row counts (data rows, header line excluded) ----
// CMD_BESANCON: ThinDisk, Bulge, ThickDisk, Halo. The lists are the
// COMPLETE Besancon population (no visibility filter; the bulge is a 3.5M random subsample of
// 7,256,344). Since bos10 (Deviation 88) they come from the noise-free catalogue bos10 with Besancon's
// own stellar types; Deviation 81 had built them from bos9, and those lists (889406 / 3500000 / 1058765 /
// 5025 rows) are kept in CMD/components_v2_bos9dev82/. CMD/components/provenance.txt has the counts.
constexpr int N1 = 1288584, N2 = 3500000, N3 = 2008646, N4 = 18541;

// ---- Mean stellar mass of each population: the mean_mass_population column of CMD/components/provenance.txt ----
// Mean stellar mass of each POPULATION (before the bulge subsample;
// dark entries included). Disk_model's star count Nstart = rho / <m>, so these make Nstart count exactly
// the population a draw comes from. bos10 values (Deviation 88); they replace the bos9 values
// 0.4212 / 0.4199 / 0.4594 / 0.3774 of Deviation 81 and, before that, the legacy 0.403445 (thin), 0.4542
// (thick, halo) and 0.308571 (bulge) of an unrecorded "mass_averaged.cpp". The Python side reads these
// through analysis/cparams.py.
constexpr double MEANMASS_THIN  = 0.3664;
constexpr double MEANMASS_BULGE = 0.4148;
constexpr double MEANMASS_THICK = 0.4849;
constexpr double MEANMASS_HALO  = 0.4224;

// ---- Visit lists ----
// Data rows in Baseline/BulgeBaseline.dat, EXCLUDING the header (lines starting with '#'). Rebuilt from
// baseline_v5.1.0_10yrs.db by Baseline/readbaselineBulge.py (Deviation 69: every pointing that can image
// the distance-rule scan region; was 3686 from a box). The earlier 7373 counted a doubled file
// (append-mode bug) and read 3687 phantom rows. Deviation 80: pointings within scan reach + 1.94 deg
// (was 12308 at + 1.75).
constexpr int Nl = 12915;

// Data rows in Baseline/RomanBaseline.dat, EXCLUDING the header. Written by
// Baseline/generateRomanBaseline.py; changes whenever the season pattern, cadence or mission start day
// changes (the read guard in src/run/inputs.cpp fires on a mismatch).
// Current: 6 high-cadence seasons (F146 every 12.1 min) + 4 low-cadence (every 5 days),
// on STScI's real alternating spring/fall visibility windows.
// `coun` in include/common.h (= Nl + NlRoman) bounds one event's light-curve buffers.
constexpr int NlRoman = 302406;

#endif // DATA_PRODUCTS_H
