#!/usr/bin/env python3
"""Generate Roman's ephemeris for VBMicrolensing: files/ephemeris/satellite1.txt and target.txt.

    .roman/bin/python tools/make_roman_l2_ephemeris.py            # write the two files
    .roman/bin/python tools/make_roman_l2_ephemeris.py --check    # write nothing; exit 1 if they are stale
    .roman/bin/python tools/make_roman_l2_ephemeris.py --root DIR # use another tree (testing)

VBMicrolensing computes satellite parallax from JPL-Horizons-format tables satellite<k>.txt, one per
observatory: the GEOCENTRIC position (RA, Dec, distance) of the satellite, daily, linearly interpolated;
`satellite = k` then selects table k (0 = the Earth). SetObjectCoordinates(file, directory) loads them,
and insists on a coordinates file in the same call.

satellite1.txt is Roman at the Sun-Earth L2 point. L2 lies on the Sun-Earth line, beyond the Earth, so
from the Earth it is in the anti-Sun direction: right ascension + 180 deg, declination -Dec of the Sun
(VBMicrolensing's own geocentric Sun table, external/VBMicrolensing/data/SunEphemeris.txt: JPL Horizons,
DE441, ICRF), at the distance L2_KM / AU_KM [AU] (config/parameters.h, read through analysis/cparams.py),
the same offset L2_OFFSET_AU the simulator's own light curve uses. Roman's halo orbit about L2 (amplitude
~1e5-1e6 km) is not modelled. The rows are on the Sun table's own grid (integer JD, 12:00 UT), so nothing
is interpolated, and cover JD 2461000 to 2465201: the simulation, MJD 61141.31 to + Tobs (2026-04 to
2036-04), plus 100 days either side.

target.txt is the coordinates file VBMicrolensing wants beside the satellite tables: one line,
"hh:mm:ss.ss -dd:mm:ss.ss" (ICRS). It is a PLACEHOLDER, the centre of the GBTDS fields (l, b) = (1.0, -1.5)
converted with astropy. The simulator sets the real target of each sightline afterwards with
SetObjectCoordinates(string) (src/events/vbm_model.cpp, vbmSetSightline), which replaces it; the satellite
tables stay loaded. The loader reads the first line only, so the comment lines after it are inert.

Deterministic: the output depends only on the Sun table and L2_KM / AU_KM, with no timestamp.
Needs numpy and astropy (the project venv).
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'analysis'))

SUN_TABLE = 'external/VBMicrolensing/data/SunEphemeris.txt'
OUT_DIR = 'files/ephemeris'
JD_FIRST, JD_LAST = 2461000, 2465201          # integer JD rows written (see the docstring)
TARGET_LB = (1.0, -1.5)                        # Galactic (l, b) [deg] of the placeholder target


def read_sun_table(path):
    """[(JD, RA deg, Dec deg, delta AU)] between $$SOE and $$EOE of a Horizons table."""
    rows, inside = [], False
    for line in Path(path).read_text().splitlines():
        if line.startswith('$$SOE'):
            inside = True
        elif line.startswith('$$EOE'):
            break
        elif inside:
            jd, ra, dec, delta = (float(x) for x in line.split()[:4])
            rows.append((jd, ra, dec, delta))
    if not rows:
        raise SystemExit('%s: no rows between $$SOE and $$EOE' % path)
    return rows


def satellite_text(sun, l2_au):
    """The satellite1.txt text: Roman at L2, the anti-Sun direction at l2_au [AU], on the Sun table's rows."""
    by_jd = {round(r[0]): r for r in sun if abs(r[0] - round(r[0])) < 1e-9}
    out = ['*' * 79,
           ' Roman Space Telescope at the Sun-Earth L2 point, for VBMicrolensing (satellite 1)',
           ' GENERATED by tools/make_roman_l2_ephemeris.py -- do not edit by hand.',
           '   .roman/bin/python tools/make_roman_l2_ephemeris.py',
           ' Position: GEOCENTRIC, in the anti-Sun direction (RA of the Sun + 180 deg, Dec of the Sun',
           ' negated), at L2_KM / AU_KM = %.14f AU (config/parameters.h). Halo orbit not modelled.' % l2_au,
           ' Source of the Sun direction: external/VBMicrolensing/data/SunEphemeris.txt (JPL Horizons,',
           ' DE441, geocentric Sun, ICRF), rows on the same integer-JD grid, so nothing is interpolated.',
           ' Layout as Horizons writes it, which is what VBMicrolensing parses: JD, RA [deg], Dec [deg],',
           ' delta [AU], deldot [km/s] (zero here), between the SOE and EOE markers.',
           '*' * 79,
           'Date_________JDUT     R.A.___(ICRF)___DEC             delta      deldot',
           '*' * 71,
           '$$SOE']
    for jd in range(JD_FIRST, JD_LAST + 1):
        if jd not in by_jd:
            raise SystemExit('the Sun table has no row at JD %d' % jd)
        _, ra, dec, _ = by_jd[jd]
        out.append('%.9f  %9.5f %9.5f  %.14f  %10.7f' % (jd, (ra + 180.0) % 360.0, -dec, l2_au, 0.0))
    out += ['$$EOE', '*' * 79, '']
    return '\n'.join(out)


def target_text(l, b):
    """The target.txt text: the placeholder target as VBMicrolensing's coordinate string, then comments."""
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    c = SkyCoord(l=l * u.deg, b=b * u.deg, frame='galactic').icrs
    return '\n'.join([c.to_string('hmsdms', sep=':', precision=2),
                      '# Placeholder target for VBMicrolensing::SetObjectCoordinates(file, directory): Galactic (l, b) = (%g, %g)' % (l, b),
                      '# deg, ICRS. Only the first line is read. The simulator replaces it per sightline (vbmSetSightline).',
                      '# GENERATED by tools/make_roman_l2_ephemeris.py -- do not edit by hand.', ''])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='write nothing; exit 1 if the files on disk are stale')
    ap.add_argument('--root', type=Path, default=ROOT, help='tree to read the Sun table from and write into')
    args = ap.parse_args()

    from cparams import load
    P = load(str(args.root))
    l2_au = P.L2_KM / P.AU_KM
    files = {'satellite1.txt': satellite_text(read_sun_table(args.root / SUN_TABLE), l2_au),
             'target.txt': target_text(*TARGET_LB)}

    stale = 0
    for name, text in files.items():
        path = args.root / OUT_DIR / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                print('stale: %s' % path)
                stale += 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print('wrote %s (%d bytes)' % (path, len(text)))
    if args.check:
        print('ephemeris files %s' % ('STALE' if stale else 'up to date'))
    return 1 if stale else 0


if __name__ == '__main__':
    sys.exit(main())
