#!/usr/bin/env python3
"""Generate config/data_products.h from the data files on disk.

The numbers in that header DESCRIBE THE DATA (row counts, catalogue mean masses, the bright-star
floor of the LSST astrometric table); they are measured here, never typed by hand.

    python3 tools/sync_data_products.py            # write config/data_products.h
    python3 tools/sync_data_products.py --check    # write nothing; exit 1 if the file on disk is stale
    python3 tools/sync_data_products.py --root DIR # use another tree (testing)

Run it from anywhere; paths resolve from this script's location (or --root). Exit codes:
0 ok / up to date, 1 --check found a stale header, 2 a data file is missing or unparseable.
The output has no timestamp, so re-running on unchanged data rewrites a byte-identical file.
Stdlib only.
"""
import argparse
import re
import sys
from pathlib import Path

COMPONENTS = [  # (provenance name, file, N constant, MEANMASS constant, analysis key)
    ("thin_disk", "CMD/components/thin_disk.dat", "N1", "MEANMASS_THIN", "thin"),
    ("bulge", "CMD/components/bulge.dat", "N2", "MEANMASS_BULGE", "bulge"),
    ("thick_disk", "CMD/components/thick_disk.dat", "N3", "MEANMASS_THICK", "thick"),
    ("halo", "CMD/components/halo.dat", "N4", "MEANMASS_HALO", "halo"),
]
PROVENANCE = "CMD/components/provenance.txt"
BULGE_BASELINE = "Baseline/BulgeBaseline.dat"
ROMAN_BASELINE = "Baseline/RomanBaseline.dat"
SIGMA_A = "files/sigmaA_LSST.txt"
SIGMA_ROMAN = "files/sigma_roman.txt"
HEADER_PATH = "config/data_products.h"


class DataError(Exception):
    pass


def need(root, rel):
    p = root / rel
    if not p.is_file():
        raise DataError(f"missing data file: {rel} (looked in {p})")
    return p


def count_rows(path, numeric_first_token=False):
    """Data rows: non-blank lines not starting with '#'. With numeric_first_token, a line only
    counts if its first token parses as a float (skips a column-name line without '#')."""
    n = 0
    with open(path, errors="replace") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            if numeric_first_token:
                try:
                    float(s.split()[0])
                except ValueError:
                    continue
            n += 1
    return n


def sigma_table(path):
    rows = []
    with open(path) as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            t = s.split()
            if len(t) < 2:
                raise DataError(f"{path}: row with fewer than 2 columns: {s!r}")
            rows.append((float(t[1]), t[1]))
    if not rows:
        raise DataError(f"{path}: no data rows")
    return len(rows), min(rows, key=lambda r: r[0])[1]


def mean_masses(path):
    """mean_mass_population per component, as the exact text, from the '# component ...' header."""
    cols, out = None, {}
    for line in open(path):
        if cols is None:
            if line.startswith("#") and "mean_mass_population" in line and line[1:].split()[:1] == ["component"]:
                cols = line[1:].split()
            continue
        t = line.split()
        if t and not line.startswith("#") and t[0] in {c[0] for c in COMPONENTS} and len(t) == len(cols):
            out[t[0]] = t[cols.index("mean_mass_population")]
    if cols is None:
        raise DataError(f"{path}: no '# component ... mean_mass_population ...' header line")
    for c in COMPONENTS:
        if c[0] not in out:
            raise DataError(f"{path}: no mean_mass_population row for {c[0]}")
    return out


def measure(root):
    v = {}
    v["Nl"] = count_rows(need(root, BULGE_BASELINE))
    v["NlRoman"] = count_rows(need(root, ROMAN_BASELINE))
    v["Na"], v["LSST_AST_TABLE_FLOOR"] = sigma_table(need(root, SIGMA_A))
    v["NaRoman"], _ = sigma_table(need(root, SIGMA_ROMAN))
    mm = mean_masses(need(root, PROVENANCE))
    for name, rel, nconst, mconst, _ in COMPONENTS:
        v[nconst] = count_rows(need(root, rel), numeric_first_token=True)
        v[mconst] = mm[name]
    return v


TEMPLATE = r'''#ifndef DATA_PRODUCTS_H
#define DATA_PRODUCTS_H

// GENERATED by tools/sync_data_products.py from the data files -- DO NOT EDIT BY HAND;
// re-run the script (python3 tools/sync_data_products.py) after regenerating any data file.
// `python3 tools/sync_data_products.py --check` (or `make check-data`) says whether this file is stale.
//
// Numbers that DESCRIBE THE DATA FILES on disk: row counts, catalogue mean masses and the bright-star
// floor of an error table. These are measurements of the data, not choices; the read guards in
// Bulge_LSST.cpp fire on a row-count mismatch. Model and survey choices live in config/parameters.h.

// ---- Error tables: files/sigmaA_LSST.txt ({Na} rows), files/sigma_roman.txt ({NaRoman} rows) ----
constexpr int Na = {Na};     //rows in "sigmaA_LSST.txt"
constexpr int NaRoman = {NaRoman};  // rows in sigma_roman.txt

// Bright-star floor of files/sigmaA_LSST.txt (its smallest error value), as shipped. config/parameters.h
// (section 4, LSST_AST_RENORM) divides the per-visit floor by it; see the note there.
constexpr double LSST_AST_TABLE_FLOOR = {LSST_AST_TABLE_FLOOR}; //mas

// ---- CMD/components/*.dat row counts (data rows, header line excluded) ----
// CMD_BESANCON: ThinDisk, Bulge, ThickDisk, Halo. The lists are the
// COMPLETE Besancon population (no visibility filter; the bulge is a 3.5M random subsample of
// 7,256,344). Since bos10 (Deviation 88) they come from the noise-free catalogue bos10 with Besancon's
// own stellar types; Deviation 81 had built them from bos9, and those lists (889406 / 3500000 / 1058765 /
// 5025 rows) are kept in CMD/components_v2_bos9dev82/. CMD/components/provenance.txt has the counts.
constexpr int N1 = {N1}, N2 = {N2}, N3 = {N3}, N4 = {N4};

// ---- Mean stellar mass of each population: the mean_mass_population column of CMD/components/provenance.txt ----
// Mean stellar mass of each POPULATION (before the bulge subsample;
// dark entries included). Disk_model's star count Nstart = rho / <m>, so these make Nstart count exactly
// the population a draw comes from. bos10 values (Deviation 88); they replace the bos9 values
// 0.4212 / 0.4199 / 0.4594 / 0.3774 of Deviation 81 and, before that, the legacy 0.403445 (thin), 0.4542
// (thick, halo) and 0.308571 (bulge) of an unrecorded "mass_averaged.cpp". The Python side reads these
// through analysis/cparams.py.
constexpr double MEANMASS_THIN  = {MEANMASS_THIN};
constexpr double MEANMASS_BULGE = {MEANMASS_BULGE};
constexpr double MEANMASS_THICK = {MEANMASS_THICK};
constexpr double MEANMASS_HALO  = {MEANMASS_HALO};

// ---- Visit lists ----
// Data rows in Baseline/BulgeBaseline.dat, EXCLUDING the header (lines starting with '#'). Rebuilt from
// baseline_v5.1.0_10yrs.db by Baseline/readbaselineBulge.py (Deviation 69: every pointing that can image
// the distance-rule scan region; was 3686 from a box). The earlier 7373 counted a doubled file
// (append-mode bug) and read 3687 phantom rows. Deviation 80: pointings within scan reach + 1.94 deg
// (was 12308 at + 1.75).
constexpr int Nl = {Nl};

// Data rows in Baseline/RomanBaseline.dat, EXCLUDING the header. Written by
// Baseline/generateRomanBaseline.py; changes whenever the season pattern, cadence or mission start day
// changes (the read guard in Bulge_LSST.cpp fires on a mismatch).
// Current: 6 high-cadence seasons (F146 every 12.1 min) + 4 low-cadence (every 5 days),
// on STScI's real alternating spring/fall visibility windows.
// `coun` in Bulge.h (= Nl + NlRoman) bounds one event's light-curve buffers.
constexpr int NlRoman = {NlRoman};

#endif // DATA_PRODUCTS_H
'''


def render(v):
    out = TEMPLATE
    for k, val in v.items():
        out = out.replace("{" + k + "}", str(val))
    return out


def parse_existing(text):
    old = {}
    for m in re.finditer(r"\b(Na|NaRoman|N[1-4]|Nl|NlRoman|MEANMASS_[A-Z]+|LSST_AST_TABLE_FLOOR)\s*=\s*([0-9.eE+-]+)\s*[,;]", text):
        old[m.group(1)] = m.group(2)
    return old


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 if the header is stale")
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                    help="repository root (default: the parent of tools/)")
    a = ap.parse_args()
    root = a.root.resolve()
    try:
        v = measure(root)
    except DataError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2
    new = render(v)
    hp = root / HEADER_PATH
    oldtext = hp.read_text() if hp.is_file() else ""
    old = parse_existing(oldtext)
    changed = []
    for k, val in v.items():
        mark = "" if old.get(k) == str(val) else f"   CHANGED (was {old.get(k, 'absent')})"
        if mark:
            changed.append(k)
        print(f"  {k:22s} = {val}{mark}")
    stale = new != oldtext
    if a.check:
        if stale:
            print(f"STALE: {HEADER_PATH} differs from what the data files give"
                  + (f" (values: {', '.join(changed)})" if changed else " (text only)")
                  + "; run python3 tools/sync_data_products.py")
            return 1
        print(f"OK: {HEADER_PATH} is up to date")
        return 0
    if stale:
        hp.write_text(new)
        print(f"wrote {HEADER_PATH}" + (f"; changed: {', '.join(changed)}" if changed else " (template text only)"))
    else:
        print(f"{HEADER_PATH}: no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
