#!/usr/bin/env python3
"""Step U7: which differences in SAMPLE DEFINITION separate our Roman black-hole characterisation
fractions from Sajadian & Sahu (2023, AJ 165, 96; arXiv:2301.03812), one at a time.

WHY THIS EXISTS. y2_ss23_compare.py matched SS23 on mass range (3-50 Msun, log-flat) and on the
denominator (fraction of Roman's detections) and still found ours at ~1/3 of theirs for tE, piE and
the mass. Reading SS23's published code (github.com/SSajadian54/AstrometryMicrolensing,
BH_Roman_V1.cpp and Analyze_IMF1.py) shows that their Table 1 is built on a different sample:
  - u0 uniform on [0, 1] (BH_Roman_V1.cpp: `l.u0=RandR(0.0,1.0)`); ours is uniform on [0, 3];
  - t0 uniform inside their 5-yr mission; our Roman detections include events peaking off-mission;
  - UNWEIGHTED counts (Analyze_IMF1.py: `numc[j]+= 1.0`) over draws made with the lens distance
    drawn from rho(Dl) sqrt(Dl (Ds-Dl)/Ds) and no sqrt(M) v_t factor -- the same sampler this
    simulator inherited; our fractions carry the event-rate weight sqrt(M) v_t Z(Ds) (Deviation 41);
  - detection dchi2 > 800 AND 3 consecutive points 4 sigma above baseline; ours dchi2 >= 500
    (not testable here: the table has no per-survey dchi2).
Each variant below changes one of these; the last combines them. Fractions are of Roman's
detections with sigma(X)/X below 1/5/10%, X in {tE, piE, tetE, Ml}, over 3-50 Msun.

    .roman/bin/python analysis/u7_ss23_factors.py --run runs/prod_bh_20260924 -o figures/u7_20260930
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import romanlib as R          # noqa: E402

COLS = ["tE", "piE", "tetE", "Ml", "Vt", "Ds", "u0", "struc", "lon", "lat", "w_area", "t0",
        "t0zone", "magb_F146", "blend_F146", "detR", "ndw_R", "opt_1e6",
        "sigtE_R", "sigpiE_R", "sigtetE_R", "relMl_R", "okA_R", "okB_R"]

# SS23 Table 1, dN/dM ~ M^-1, sparse observations during the gap [%] (as in y2_ss23_compare.py)
SS23 = {0.01: {"tE": 24.48, "piE": 7.55, "tetE": 67.89, "Ml": 5.30},
        0.05: {"tE": 54.23, "piE": 21.38, "tetE": 96.75, "Ml": 20.81},
        0.10: {"tE": 66.95, "piE": 30.00, "tetE": 99.17, "Ml": 29.79}}
PARAMS = ["tE", "piE", "tetE", "Ml"]


def rel_error(df, p):
    s = R.sigma(df, p, "roman")
    return s if p == "Ml" else s / df[p].astype(float)


def fractions(df, w, sel):
    """Weighted % of the selected Roman detections with sigma/X below each threshold."""
    det = R.detected(df, "roman") & sel
    tot = w.where(det, 0.0).sum()
    out = {}
    for thr in SS23:
        for p in PARAMS:
            r = rel_error(df, p)
            good = det & r.notna() & (r < thr)
            out[(thr, p)] = 100.0 * w.where(good, 0.0).sum() / tot
    return out, int(det.sum()), R.kish_neff(w[det])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--run", required=True)
    ap.add_argument("-o", "--out-dir", required=True)
    a = ap.parse_args()
    ev = os.path.join(a.run, "testbh_detJ.dat")
    mp = os.path.join(a.run, "files/MONTLMC/files/MapLMCbh.dat")
    logs = [os.path.join(a.run, "run.log")]
    df = R.load_events(ev, usecols=COLS)
    df = df[(df.Ml >= 3.0) & (df.Ml <= 50.0)].copy()
    w, wlabel = R.attach_weight(df, map_path=mp, log_paths=logs)
    ones = pd.Series(1.0, index=df.index)
    u0le1 = df.u0 <= 1.0
    onmission = df.t0zone.isin([0, 1])
    allrows = pd.Series(True, index=df.index)

    variants = [
        ("ours (event-rate weighted, u0 <= 3)", w, allrows),
        ("u0 <= 1 only", w, u0le1),
        ("t0 on Roman's mission only", w, onmission),
        ("unweighted only (SS23's counting)", ones, allrows),
        ("SS23 sample: unweighted, u0 <= 1, t0 on mission", ones, u0le1 & onmission),
    ]
    os.makedirs(a.out_dir, exist_ok=True)
    rows, lines = [], ["# Roman black-hole characterisation vs Sajadian & Sahu 2023: sample-definition factors",
                       "", f"Generated by `analysis/u7_ss23_factors.py` from `{ev}`; 3-50 Msun (log-flat as drawn); "
                       f"weights: {wlabel}. Percent of Roman's detections with sigma(X)/X below the threshold.", ""]
    for name, wt, sel in variants:
        fr, n, neff = fractions(df, wt, sel)
        lines.append(f"\n### {name}\n\nRoman detections: {n:,} draws, N_eff {neff:,.0f}\n")
        lines.append("| threshold | " + " | ".join(PARAMS) + " |")
        lines.append("|---|" + "---:|" * len(PARAMS))
        for thr in SS23:
            lines.append(f"| <{thr:.0%} | " + " | ".join(
                f"{fr[(thr, p)]:.1f} ({fr[(thr, p)] / SS23[thr][p]:.2f})" for p in PARAMS) + " |")
            for p in PARAMS:
                rows.append(dict(variant=name, threshold=thr, param=p, ours=fr[(thr, p)],
                                 ss23=SS23[thr][p], ratio=fr[(thr, p)] / SS23[thr][p], n=n, neff=neff))
    lines.append("\nCells: ours (ours / SS23). SS23 = Table 1, dN/dM ~ M^-1, sparse observations.")
    # The sample itself, against SS23's Fig. 3 (their detected events: <tE> 303 d, <m_base> 20.06
    # for the UNIFORM mass function; u0 flat on [0, 1], mean 0.49).
    det = R.detected(df, "roman")
    lines.append("\n### Roman detections, 3-50 Msun: sample properties (unweighted, as SS23 plot them)\n")
    for lab, sel in [("all", det), ("SS23 sample", det & u0le1 & onmission)]:
        d = df[sel]
        lines.append(f"- {lab}: mean tE {d.tE.mean():.0f} d (median {d.tE.median():.0f}), mean u0 "
                     f"{d.u0.mean():.2f}, share u0 > 1 {100 * (d.u0 > 1).mean():.1f}%, mean m_base(F146) "
                     f"{d.magb_F146.mean():.2f}, median fb(F146) {d.blend_F146.median():.3f}, median piE "
                     f"{d.piE.median():.4f}, share off-mission {100 * (~d.t0zone.isin([0, 1])).mean():.1f}%")
    txt = "\n".join(lines) + "\n"
    with open(os.path.join(a.out_dir, "u7_ss23_factors.md"), "w") as fh:
        fh.write(txt)
    pd.DataFrame(rows).to_csv(os.path.join(a.out_dir, "u7_ss23_factors.csv"), index=False)
    print(txt)


if __name__ == "__main__":
    main()
